# Generated by Django 6.1.1 on 2026-09-17 23:25

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0002_alter_workspace_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('destination_url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('favicon_url', models.URLField(blank=True, max_length=1024)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='active', max_length=10)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.CharField(blank=True, max_length=400)),
                ('og_image_url', models.URLField(blank=True, max_length=1024)),
                ('og_overridden', models.BooleanField(default=False)),
                ('og_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_clicks', models.PositiveIntegerField(blank=True, null=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='workspaces.workspace')),
                ('tags', models.ManyToManyField(blank=True, related_name='links', to='links.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LinkTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('desktop', 'Desktop')], max_length=10)),
                ('url', models.URLField(blank=True, max_length=2048)),
                ('app_url', models.CharField(blank=True, max_length=2048)),
                ('fallback_url', models.URLField(blank=True, max_length=2048)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='links.link')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('link', 'platform'), name='links_target_platform_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(models.F('workspace'), django.db.models.functions.text.Lower('name'), name='links_tag_workspace_name_unique'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['workspace', '-created_at'], name='links_link_workspa_eda082_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['workspace', 'status'], name='links_link_workspa_f37cdd_idx'),
        ),
        migrations.AddConstraint(
            model_name='link',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='links_link_code_ci_unique'),
        ),
    ]
