# Generated by Django 6.1.1 on 2026-09-17 22:39

import apps.workspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64, validators=[apps.workspaces.models.validate_timezone]),
        ),
    ]
