# Generated by Django 6.1.1 on 2026-09-18 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('links', '0001_initial'),
        ('workspaces', '0002_alter_workspace_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLinkBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('dimension', models.CharField(choices=[('country', 'Country'), ('city', 'City'), ('referrer', 'Referrer'), ('device', 'Device'), ('os', 'Operating system'), ('browser', 'Browser'), ('utm_source', 'UTM source'), ('utm_medium', 'UTM medium'), ('utm_campaign', 'UTM campaign'), ('target_platform', 'Target platform')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_breakdowns', to='links.link')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_breakdowns', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-clicks'],
                'indexes': [models.Index(fields=['workspace', 'date', 'dimension'], name='analytics_d_workspa_4511a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('link', 'date', 'dimension', 'value'), name='analytics_daily_breakdown_unique')],
            },
        ),
        migrations.CreateModel(
            name='DailyLinkStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('bot_clicks', models.PositiveIntegerField(default=0)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='links.link')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['workspace', '-date'], name='analytics_d_workspa_dc82e8_idx')],
                'constraints': [models.UniqueConstraint(fields=('link', 'date'), name='analytics_daily_stat_unique')],
            },
        ),
    ]
