# Generated by Django 6.1.1 on 2026-09-18 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rollups'),
        ('links', '0001_initial'),
        ('workspaces', '0002_alter_workspace_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClickIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('identity', models.CharField(max_length=64)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_identities', to='links.link')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_identities', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'date'], name='analytics_d_workspa_d6f5c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('link', 'date', 'identity'), name='analytics_daily_identity_unique')],
            },
        ),
    ]
