# Generated by Django 6.1.1 on 2026-09-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_dailyclickidentity'),
        ('links', '0001_initial'),
        ('workspaces', '0002_alter_workspace_timezone'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailylinkbreakdown',
            name='analytics_d_workspa_4511a5_idx',
        ),
        migrations.AddField(
            model_name='dailylinkbreakdown',
            name='bot_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='dailyclickidentity',
            index=models.Index(fields=['date'], name='analytics_identity_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailylinkbreakdown',
            index=models.Index(fields=['workspace', 'dimension', 'date'], name='analytics_d_workspa_d5147a_idx'),
        ),
    ]
